swagger: "2.0"
info:
  description: This is the swagger file that describes the functionality of this api. To make a request, remove /ui and
   add the relevant path. Supported tickers can be found from /options/getAllTickers. I have recently added many more symbols.
   Enjoy! Feel free to contact me with questions. If you use this data frequently, please considering donating to https://paypal.me/StephenFanale?locale.x=en_US
   so I can keep paying AWS to host this data.
  version: "1.0.0"
  title: Fanale Research Option Data Api
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /options/{ticker}:
      get:
        operationId: get_options_prices.read_list
        tags:
          - options
        summary: Get list of options contracts for one stock symbol. Can specify by minimum expiration date or strike price
          as well. e.q. 'AAPL&200&1577836800'. Date or strike or both can be empty but ticker must be specified.
        description: Get all contracts for one stock
        parameters:
          - name: ticker
            in: path
            description: Stock ticker symbol for asset
            type: string
            required: True
        responses:
          200:
            description: Successfully found stock
            schema:
              type: array
              items:
                properties:
                  symbol:
                    type: string
                  contractsymbol:
                    type: string
                  timestamp:
                    type: string

  /options/detail/{contractsymbol}:
      get:
        operationId: get_options_prices.read_one_symbol
        tags:
          - options
        summary: Get all information about a single contract
        description: Get all option data for one contract
        parameters:
          - name: contractsymbol
            in: path
            description: Contract Symbole for option
            type: string
            required: True
        responses:
          200:
            description: Successfully found contract details
            schema:
              type: array
              items:
                properties:
                  expiry:
                    type: string
                  strike:
                    type: string
                  lastprice:
                    type: string
                  pricedate:
                    type: string
                  optiontype:
                    type: string
                  bid:
                    type: string
                  ask:
                    type: string
                  openinterest:
                    type: string
                  volume:
                    type: string
                  symbol:
                    type: string
                  sector:
                    type: string
                  industry:
                    type: string
                  timestamp:
                    type: string


  /options/all/{ticker}:
      get:
        operationId: get_options_prices.read_one_all
        tags:
          - options
        summary: Get all options data for all contracts for one asset
        description: Get all options data for one asset. dates are in NY local unix time,.
        parameters:
          - name: ticker
            in: path
            description: Stock ticker symbol for asset
            type: string
            required: True
        responses:
          200:
            description: Successfully found stock
            schema:
              type: array
              items:
                properties:
                  symbol:
                    type: string
                  contractsymbol:
                    type: string
                  expiry:
                    type: string
                  strike:
                    type: string
                  lastprice:
                    type: string
                  pricedate:
                    type: string
                  optiontype:
                    type: string
                  bid:
                    type: string
                  ask:
                    type: string
                  openinterest:
                    type: string
                  volume:
                    type: string
                  sector:
                    type: string
                  industry:
                    type: string
                  timestamp:
                    type: string

  /quotes/{ticker}:
      get:
        operationId: get_stock_prices.read_list
        tags:
          - stocks
        summary: Get price data for one stock/etf
        description: Get all prices for one stock/etf
        parameters:
          - name: ticker
            in: path
            description: Stock ticker symbol for asset
            type: string
            required: True
        responses:
          200:
            description: Successfully found stock
            schema:
              type: array
              items:
                properties:
                  symbol:
                    type: string
                  pricedate:
                    type: string
                  closep:
                    type: string
                  volume:
                    type: string
                  timestamp:
                    type: string


  /options/getAllTickers:
      get:
        operationId: get_options_prices.getAllTickers
        tags:
          - options
        summary: Get list of all symbols with options data
        description: Get all symbols with options data
        responses:
          200:
            description: Successfull
            schema:
              type: array
              items:
                properties:
                  symbol:
                    type: string
